<template>
	<div class="panel-color d-flex align-items-start justify-content-center">
		<div class="d-flex flex-column">
			<button type="button" @click="changeColor('#000000')" style="background-color:#000000;">黒</button>
			<button type="button" @click="changeColor('#ffffff')" style="background-color:#ffffff;color:#333;">白</button>
			<button type="button" @click="changeColor('#808080')" style="background-color:#808080;">灰</button>
		</div>
		<div class="d-flex flex-column">
			<button type="button" @click="changeColor('#ff0000')" style="background-color:#ff0000;">赤</button>
			<button type="button" @click="changeColor('#ff7f00')" style="background-color:#ff7f00;">橙</button>
			<button type="button" @click="changeColor('#ffff07')" style="background-color:#ffff07;">黄</button>
			<button type="button" @click="changeColor('#008737')" style="background-color:#008737;">緑</button>
			<button type="button" @click="changeColor('#009fc5')" style="background-color:#009fc5;">青</button>
			<button type="button" @click="changeColor('#0950a0')" style="background-color:#0950a0;">藍</button>
			<button type="button" @click="changeColor('#0f218a')" style="background-color:#0f218a;">紺</button>
			<button type="button" @click="changeColor('#80057e')" style="background-color:#80057e;">紫</button>
			<button type="button" @click="changeColor('#ef057f')" style="background-color:#ef057f;">紅</button>
			<button type="button" @click="changeColor('#f680be')" style="background-color:#f680be;">桃</button>
		</div>
		<div class="d-flex flex-wrap custom">
			<button type="button" @click="changeColor('#b5184f')" style="background-color:#b5184f;">&nbsp;</button>
			<button type="button" @click="changeColor('#cd1f42')" style="background-color:#cd1f42;">&nbsp;</button>
			<button type="button" @click="changeColor('#dd3737')" style="background-color:#dd3737;">&nbsp;</button>
			<button type="button" @click="changeColor('#e55025')" style="background-color:#e55025;">&nbsp;</button>
			<button type="button" @click="changeColor('#e66e00')" style="background-color:#e66e00;">&nbsp;</button>
			<button type="button" @click="changeColor('#f39501')" style="background-color:#f39501;">&nbsp;</button>
			<button type="button" @click="changeColor('#eeac00')" style="background-color:#eeac00;">&nbsp;</button>
			<button type="button" @click="changeColor('#e4c400')" style="background-color:#e4c400;">&nbsp;</button>
			<button type="button" @click="changeColor('#cabb00')" style="background-color:#cabb00;">&nbsp;</button>
			<button type="button" @click="changeColor('#aab300')" style="background-color:#aab300;">&nbsp;</button>
			<button type="button" @click="changeColor('#4aa315')" style="background-color:#4aa315;">&nbsp;</button>
			<button type="button" @click="changeColor('#009a54')" style="background-color:#009a54;">&nbsp;</button>
			<button type="button" @click="changeColor('#008c69')" style="background-color:#008c69;">&nbsp;</button>
			<button type="button" @click="changeColor('#017e78')" style="background-color:#017e78;">&nbsp;</button>
			<button type="button" @click="changeColor('#017c8c')" style="background-color:#017c8c;">&nbsp;</button>
			<button type="button" @click="changeColor('#006c93')" style="background-color:#006c93;">&nbsp;</button>
			<button type="button" @click="changeColor('#005991')" style="background-color:#005991;">&nbsp;</button>
			<button type="button" @click="changeColor('#00569d')" style="background-color:#00569d;">&nbsp;</button>
			<button type="button" @click="changeColor('#01509d')" style="background-color:#01509d;">&nbsp;</button>
			<button type="button" @click="changeColor('#464799')" style="background-color:#464799;">&nbsp;</button>
			<button type="button" @click="changeColor('#673e8c')" style="background-color:#673e8c;">&nbsp;</button>
			<button type="button" @click="changeColor('#793580')" style="background-color:#793580;">&nbsp;</button>
			<button type="button" @click="changeColor('#892c72')" style="background-color:#892c72;">&nbsp;</button>
			<button type="button" @click="changeColor('#ab2665')" style="background-color:#ab2665;">&nbsp;</button>
			<button type="button" @click="changeColor('#d75674')" style="background-color:#d75674;">&nbsp;</button>
			<button type="button" @click="changeColor('#f15d69')" style="background-color:#f15d69;">&nbsp;</button>
			<button type="button" @click="changeColor('#f06057')" style="background-color:#f06057;">&nbsp;</button>
			<button type="button" @click="changeColor('#f7764c')" style="background-color:#f7764c;">&nbsp;</button>
			<button type="button" @click="changeColor('#fc8d3e')" style="background-color:#fc8d3e;">&nbsp;</button>
			<button type="button" @click="changeColor('#fba52e')" style="background-color:#fba52e;">&nbsp;</button>
			<button type="button" @click="changeColor('#f9bb2c')" style="background-color:#f9bb2c;">&nbsp;</button>
			<button type="button" @click="changeColor('#f2d323')" style="background-color:#f2d323;">&nbsp;</button>
			<button type="button" @click="changeColor('#d9c71b')" style="background-color:#d9c71b;">&nbsp;</button>
			<button type="button" @click="changeColor('#b7c019')" style="background-color:#b7c019;">&nbsp;</button>
			<button type="button" @click="changeColor('#77bb4c')" style="background-color:#77bb4c;">&nbsp;</button>
			<button type="button" @click="changeColor('#00b276')" style="background-color:#00b276;">&nbsp;</button>
			<button type="button" @click="changeColor('#00a583')" style="background-color:#00a583;">&nbsp;</button>
			<button type="button" @click="changeColor('#00a49d')" style="background-color:#00a49d;">&nbsp;</button>
			<button type="button" @click="changeColor('#0094a2')" style="background-color:#0094a2;">&nbsp;</button>
			<button type="button" @click="changeColor('#008eb2')" style="background-color:#008eb2;">&nbsp;</button>
			<button type="button" @click="changeColor('#007daf')" style="background-color:#007daf;">&nbsp;</button>
			<button type="button" @click="changeColor('#1a79bd')" style="background-color:#1a79bd;">&nbsp;</button>
			<button type="button" @click="changeColor('#4d73ba')" style="background-color:#4d73ba;">&nbsp;</button>
			<button type="button" @click="changeColor('#716bb5')" style="background-color:#716bb5;">&nbsp;</button>
			<button type="button" @click="changeColor('#8b63ac')" style="background-color:#8b63ac;">&nbsp;</button>
			<button type="button" @click="changeColor('#9b5da0')" style="background-color:#9b5da0;">&nbsp;</button>
			<button type="button" @click="changeColor('#ab5792')" style="background-color:#ab5792;">&nbsp;</button>
			<button type="button" @click="changeColor('#cc5b87')" style="background-color:#cc5b87;">&nbsp;</button>
			<button type="button" @click="changeColor('#c23546')" style="background-color:#c23546;">&nbsp;</button>
			<button type="button" @click="changeColor('#c7512d')" style="background-color:#c7512d;">&nbsp;</button>
			<button type="button" @click="changeColor('#dc8b08')" style="background-color:#dc8b08;">&nbsp;</button>
			<button type="button" @click="changeColor('#d1b700')" style="background-color:#d1b700;">&nbsp;</button>
			<button type="button" @click="changeColor('#99a400')" style="background-color:#99a400;">&nbsp;</button>
			<button type="button" @click="changeColor('#008953')" style="background-color:#008953;">&nbsp;</button>
			<button type="button" @click="changeColor('#007b76')" style="background-color:#007b76;">&nbsp;</button>
			<button type="button" @click="changeColor('#006a8a')" style="background-color:#006a8a;">&nbsp;</button>
			<button type="button" @click="changeColor('#005693')" style="background-color:#005693;">&nbsp;</button>
			<button type="button" @click="changeColor('#4b488d')" style="background-color:#4b488d;">&nbsp;</button>
			<button type="button" @click="changeColor('#753a7c')" style="background-color:#753a7c;">&nbsp;</button>
			<button type="button" @click="changeColor('#a13664')" style="background-color:#a13664;">&nbsp;</button>
			<button type="button" @click="changeColor('#9f1b33')" style="background-color:#9f1b33;">&nbsp;</button>
			<button type="button" @click="changeColor('#a63b1b')" style="background-color:#a63b1b;">&nbsp;</button>
			<button type="button" @click="changeColor('#a58e00')" style="background-color:#a58e00;">&nbsp;</button>
			<button type="button" @click="changeColor('#727c01')" style="background-color:#727c01;">&nbsp;</button>
			<button type="button" @click="changeColor('#006e3d')" style="background-color:#006e3d;">&nbsp;</button>
			<button type="button" @click="changeColor('#00625d')" style="background-color:#00625d;">&nbsp;</button>
			<button type="button" @click="changeColor('#01526f')" style="background-color:#01526f;">&nbsp;</button>
			<button type="button" @click="changeColor('#014075')" style="background-color:#014075;">&nbsp;</button>
			<button type="button" @click="changeColor('#353374')" style="background-color:#353374;">&nbsp;</button>
			<button type="button" @click="changeColor('#59265f')" style="background-color:#59265f;">&nbsp;</button>
			<button type="button" @click="changeColor('#801f4c')" style="background-color:#801f4c;">&nbsp;</button>
			<button type="button" @click="changeColor('#f38c8f')" style="background-color:#f38c8f;">&nbsp;</button>
			<button type="button" @click="changeColor('#ff9e7d')" style="background-color:#ff9e7d;">&nbsp;</button>
			<button type="button" @click="changeColor('#fcb769')" style="background-color:#fcb769;">&nbsp;</button>
			<button type="button" @click="changeColor('#eed267')" style="background-color:#eed267;">&nbsp;</button>
			<button type="button" @click="changeColor('#cbca60')" style="background-color:#cbca60;">&nbsp;</button>
			<button type="button" @click="changeColor('#73c99c')" style="background-color:#73c99c;">&nbsp;</button>
			<button type="button" @click="changeColor('#40aba5')" style="background-color:#40aba5;">&nbsp;</button>
			<button type="button" @click="changeColor('#52a6c0')" style="background-color:#52a6c0;">&nbsp;</button>
			<button type="button" @click="changeColor('#6591c2')" style="background-color:#6591c2;">&nbsp;</button>
			<button type="button" @click="changeColor('#8e87bd')" style="background-color:#8e87bd;">&nbsp;</button>
			<button type="button" @click="changeColor('#ac7ead')" style="background-color:#ac7ead;">&nbsp;</button>
			<button type="button" @click="changeColor('#d98197')" style="background-color:#d98197;">&nbsp;</button>
			<button type="button" @click="changeColor('#f59fa2')" style="background-color:#f59fa2;">&nbsp;</button>
			<button type="button" @click="changeColor('#feb195')" style="background-color:#feb195;">&nbsp;</button>
			<button type="button" @click="changeColor('#ffc887')" style="background-color:#ffc887;">&nbsp;</button>
			<button type="button" @click="changeColor('#f9e18b')" style="background-color:#f9e18b;">&nbsp;</button>
			<button type="button" @click="changeColor('#d9d784')" style="background-color:#d9d784;">&nbsp;</button>
			<button type="button" @click="changeColor('#90d4af')" style="background-color:#90d4af;">&nbsp;</button>
			<button type="button" @click="changeColor('#73c4be')" style="background-color:#73c4be;">&nbsp;</button>
			<button type="button" @click="changeColor('#70b0c9')" style="background-color:#70b0c9;">&nbsp;</button>
			<button type="button" @click="changeColor('#7d9dc3')" style="background-color:#7d9dc3;">&nbsp;</button>
			<button type="button" @click="changeColor('#9c95c1')" style="background-color:#9c95c1;">&nbsp;</button>
			<button type="button" @click="changeColor('#b38eb7')" style="background-color:#b38eb7;">&nbsp;</button>
			<button type="button" @click="changeColor('#d995ac')" style="background-color:#d995ac;">&nbsp;</button>
			<button type="button" @click="changeColor('#c9777b')" style="background-color:#c9777b;">&nbsp;</button>
			<button type="button" @click="changeColor('#d6896f')" style="background-color:#d6896f;">&nbsp;</button>
			<button type="button" @click="changeColor('#d59f61')" style="background-color:#d59f61;">&nbsp;</button>
			<button type="button" @click="changeColor('#ccb663')" style="background-color:#ccb663;">&nbsp;</button>
			<button type="button" @click="changeColor('#aeac5f')" style="background-color:#aeac5f;">&nbsp;</button>
			<button type="button" @click="changeColor('#66a986')" style="background-color:#66a986;">&nbsp;</button>
			<button type="button" @click="changeColor('#4a9b95')" style="background-color:#4a9b95;">&nbsp;</button>
			<button type="button" @click="changeColor('#498a9e')" style="background-color:#498a9e;">&nbsp;</button>
			<button type="button" @click="changeColor('#59779b')" style="background-color:#59779b;">&nbsp;</button>
			<button type="button" @click="changeColor('#766f99')" style="background-color:#766f99;">&nbsp;</button>
			<button type="button" @click="changeColor('#8b698c')" style="background-color:#8b698c;">&nbsp;</button>
			<button type="button" @click="changeColor('#ae6f84')" style="background-color:#ae6f84;">&nbsp;</button>
			<button type="button" @click="changeColor('#9c5457')" style="background-color:#9c5457;">&nbsp;</button>
			<button type="button" @click="changeColor('#a9624e')" style="background-color:#a9624e;">&nbsp;</button>
			<button type="button" @click="changeColor('#a9783e')" style="background-color:#a9783e;">&nbsp;</button>
			<button type="button" @click="changeColor('#a18e41')" style="background-color:#a18e41;">&nbsp;</button>
			<button type="button" @click="changeColor('#85853b')" style="background-color:#85853b;">&nbsp;</button>
			<button type="button" @click="changeColor('#418260')" style="background-color:#418260;">&nbsp;</button>
			<button type="button" @click="changeColor('#1c7573')" style="background-color:#1c7573;">&nbsp;</button>
			<button type="button" @click="changeColor('#1e6577')" style="background-color:#1e6577;">&nbsp;</button>
			<button type="button" @click="changeColor('#335473')" style="background-color:#335473;">&nbsp;</button>
			<button type="button" @click="changeColor('#514d72')" style="background-color:#514d72;">&nbsp;</button>
			<button type="button" @click="changeColor('#854c5f')" style="background-color:#854c5f;">&nbsp;</button>
			<button type="button" @click="changeColor('#652a2e')" style="background-color:#652a2e;">&nbsp;</button>
			<button type="button" @click="changeColor('#6f3726')" style="background-color:#6f3726;">&nbsp;</button>
			<button type="button" @click="changeColor('#704a19')" style="background-color:#704a19;">&nbsp;</button>
			<button type="button" @click="changeColor('#6b5e1a')" style="background-color:#6b5e1a;">&nbsp;</button>
			<button type="button" @click="changeColor('#555517')" style="background-color:#555517;">&nbsp;</button>
			<button type="button" @click="changeColor('#195138')" style="background-color:#195138;">&nbsp;</button>
			<button type="button" @click="changeColor('#004542')" style="background-color:#004542;">&nbsp;</button>
			<button type="button" @click="changeColor('#004252')" style="background-color:#004252;">&nbsp;</button>
			<button type="button" @click="changeColor('#14344d')" style="background-color:#14344d;">&nbsp;</button>
			<button type="button" @click="changeColor('#312e4d')" style="background-color:#312e4d;">&nbsp;</button>
			<button type="button" @click="changeColor('#422a44')" style="background-color:#422a44;">&nbsp;</button>
			<button type="button" @click="changeColor('#5d2c3f')" style="background-color:#5d2c3f;">&nbsp;</button>
		</div>
	</div>
</template>
<script setup>
const props = defineProps({
	operation: Object,
});

const changeColor = (color) => props.operation.changeColor(color);
</script>
